export const historial = [
    {
        transf_id: 0,
        transf_desc: 'Pago amigos',
        transf_mount: 500,
        transf_dest: 'Pablo Rago',
        transf_date: '12 SEP',
    },
    {
        transf_id: 1,
        transf_desc: 'Recarga',
        transf_mount: 1500,
        transf_dest: 'Claro',
        transf_date: '4 SEP',
    },
    {
        transf_id: 2,
        transf_desc: 'Compra despensa',
        transf_mount: 4500,
        transf_dest: 'Despensa el buen coder',
        transf_date: '1 SEP',
    },
    {
        transf_id: 3,
        transf_desc: 'Netflix',
        transf_mount: 600,
        transf_dest: 'Netflix',
        transf_date: '16 AGO',
    },
    {
        transf_id: 0,
        transf_desc: 'Pago amigos',
        transf_mount: 500,
        transf_dest: 'Pablo Rago',
        transf_date: '12 AGO',
    },
    {
        transf_id: 1,
        transf_desc: 'Recarga',
        transf_mount: 1500,
        transf_dest: 'Claro',
        transf_date: '30 MAY',
    },
    {
        transf_id: 2,
        transf_desc: 'Compra despensa',
        transf_mount: 4500,
        transf_dest: 'Despensa el buen coder',
        transf_date: '10 ABR',
    },
    {
        transf_id: 3,
        transf_desc: 'Netflix',
        transf_mount: 600,
        transf_dest: 'Netflix',
        transf_date: '20 MAR',
    },
]
